In [1]:
import os
import pandas as pd
import requests
import spotipy
from IPython.display import display
from spotipy.oauth2 import SpotifyClientCredentials, SpotifyOAuth
from dotenv import find_dotenv, load_dotenv

dotenv_path = find_dotenv(usecwd=True)
loaded = load_dotenv(dotenv_path=dotenv_path)
print(f"dotenv_loaded={loaded}, dotenv_path={dotenv_path}")

dotenv_loaded=True, dotenv_path=/Users/Marcy_Student/Desktop/Spotify_Project/.env

In [4]:
# setting up credentials
def get_spotify_client():
    spotify_client_id = os.getenv("SPOTIFY_CLIENT_ID")
    spotify_client_secret = os.getenv("SPOTIFY_CLIENT_SECRET") 

    auth_manager = SpotifyClientCredentials(
        client_id=spotify_client_id,
        client_secret=spotify_client_secret)
    
    sp = spotipy.Spotify(auth_manager=auth_manager)
    
    return sp



print("Spotify configuration loaded")

sp = get_spotify_client()

Spotify configuration loaded

In [5]:
# testing spotipy with my fav artist NF
from IPython.display import display
query = "artist:NF"
album_results = sp.search(q=query, type="album", limit=10)
track_results = sp.search(q=query, type="track", limit=10)
albums = [
    {
        "album": item["name"],
        "album_type": item["album_type"],
        "release_date": item["release_date"],
        "total_tracks": item["total_tracks"],
    }
    for item in album_results["albums"]["items"]
]
tracks = [
    {

        "track": item["name"],
        "album": item["album"]["name"],
        "artists": ", ".join(artist["name"] for artist in item["artists"]),
        "preview_url": item.get("preview_url"),
    }
    for item in track_results["tracks"]["items"]
]
print("NF albums")
display(pd.DataFrame(albums))
print("NF tracks")
display(pd.DataFrame(tracks))

NF albums

                  album album_type release_date  total_tracks
0                  FEAR     single   2025-11-14             6
1                  HOPE     single   2023-02-16             1
2             WHO I WAS     single   2025-11-13             1
3  CLOUDS (THE MIXTAPE)      album   2021-03-26            11
4                  HOPE      album   2023-04-07            13
5               Cookout     single   2026-06-07             1
6               Mansion      album   2015-03-31            12
7            Perception      album   2017-10-06            16
8            The Search      album   2019-07-26            20
9       Therapy Session      album   2016-04-22            14

NF tracks

          track       album artists preview_url
0  Let You Down  Perception      NF        None
1          FEAR        FEAR      NF        None
2         HAPPY        HOPE      NF        None
3           Lie  Perception      NF        None
4    The Search  The Search      NF        None

In [ ]:
headers = {
    "x-rapidapi-key": rapidapi_key,
    "x-rapidapi-host": rapidapi_host,
    "Content-Type": "application/json",
}
rapidapi_key = os.getenv("RAPIDAPI_KEY")
rapidapi_host = "track-analysis.p.rapidapi.com"